permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
# paginate: 5
# paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
masthead_title: Home
title: "Hamidreza Sanaee"
logo: "https://raw.githubusercontent.com/HamidrezaSK/HamidrezaSK.github.io/master/images/avatar.jpg"
description: "Software Engineer"
masthead_bio: "Hi, I'm Hamid. I'm a final year Master's student in Software Engineering and Cloud Computing based in London. I like to dive into challenging problems and look for the light. Embedded Software Engineering and Compiler Engineering are fascinating areas of interest that I enjoy exploring."
  #twitter:
  #username: roidrage

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

search: true

author:
  name: "Hamidreza Sanaee"
  location: "London, England"
  picture: https://raw.githubusercontent.com/HamidrezaSK/HamidrezaSK.github.io/master/images/avatar.jpg
  bio: "Software Engineer"
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/HamidrezaSK"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hamidreza-sanaee-05aba817b/"
    - label: "Contact Me"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:shrsanaee@gmail.com"

footer_links:
  - title: "Github"
    icon: "fab fa-fw fa-github-square"
    url: "https://github.com/HamidrezaSK"
  - title: "Contact Me"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:shrsanaee@gmail.com"
  - title: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/hamidreza-sanaee-05aba817b/"

url: "https://github.com/HamidrezaSK"
feed:
  path: feed.xml

defaults:
  # _posts
  defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

locale: en-US

# copyright: 2007-2021 Mathias Meyer ([Legal](/legal/))

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
