markdown: kramdown
permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
paginate: 3
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives
theme: minimal-mistakes-jekyll
masthead_title: Mathias Meyer
title: Mathias Meyer
atom_feed: /atom.xml
search: false
twitter:
  username: roidrage

minimal_mistakes_skin: air

author:
  name: "Mathias Meyer"
  location: "Berlin, Germany"
  avatar: /images/mathias_meyer_square.jpg
  bio: "Executive Leadership Coach to Founders and CTOs"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/roidrage"
    - label: "Contact Me"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/mathias-meyer-50a753aa/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/roidrage"
    - label: "Contact Me"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"
    - label: "Legal"
      url: "/legal/"

words_per_minute: 200
url: "https://www.paperplanes.de"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      classes: wide

locale: en-US

tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive-taxonomy
  permalinks:
    tag: /tags/:name/
