permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
paginate: 5
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives
theme: jekyll-theme-so-simple
masthead_title: Home
title: "Mathias Meyer"
logo: "https://intentionalorganization.com/img/a3ded2d0-400.jpeg"
description: "Executive leadership coaching for founders, executives, and entrepreneurs<br/>based on inclusion, clarity, and learning."
twitter:
  username: roidrage

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

search: true

author:
  name: "Mathias Meyer"
  location: "Berlin, Germany"
  picture: https://intentionalorganization.com/img/a3ded2d0-400.jpeg
  bio: "Executive Leadership Coach to Founders and CTOs"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/roidrage"
    - label: "Contact Me"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/mathias-meyer-50a753aa/"

footer_links:
  - title: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/roidrage"
  - title: "Contact Me"
    icon: "fas fa-fw fa-envelope-square"
    url: "/contact/"
  - title: "Legal"
    url: "/legal/"

url: "https://www.paperplanes.de"
defaults:
  # _posts
  defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

locale: en-US

copyright: 2007-2021 Mathias Meyer
